/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Luís Felipe
 */
public class VendasConsultar_GUI extends javax.swing.JFrame {

    /**
     * Creates new form VendasConsultar_GUI
     */
    public VendasConsultar_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cpf4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cliente4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vendedor4 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cod4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        data4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        total4 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        hora4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        metodo4 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela_Vendas = new javax.swing.JTable();
        buttonSeven11 = new org.edisoncor.gui.button.ButtonSeven();
        buttonSeven12 = new org.edisoncor.gui.button.ButtonSeven();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMinimumSize(new java.awt.Dimension(650, 480));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTAR VENDAS");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 20, 400, 30);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CPF do Cliente:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 50, 100, 20);

        cpf4.setBackground(new java.awt.Color(0, 153, 153));
        cpf4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cpf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpf4ActionPerformed(evt);
            }
        });
        jPanel2.add(cpf4);
        cpf4.setBounds(130, 50, 90, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nome do Cliente:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(280, 20, 110, 20);

        cliente4.setBackground(new java.awt.Color(0, 153, 153));
        cliente4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cliente4ActionPerformed(evt);
            }
        });
        jPanel2.add(cliente4);
        cliente4.setBounds(400, 20, 110, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nome do Vendedor:");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(280, 50, 130, 20);

        vendedor4.setBackground(new java.awt.Color(0, 153, 153));
        vendedor4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        vendedor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendedor4ActionPerformed(evt);
            }
        });
        jPanel2.add(vendedor4);
        vendedor4.setBounds(420, 50, 110, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CÓDIGO da Venda:");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 20, 130, 20);

        cod4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cod4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cod4ActionPerformed(evt);
            }
        });
        jPanel2.add(cod4);
        cod4.setBounds(170, 20, 50, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Data da Venda:");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 110, 100, 20);

        data4.setBackground(new java.awt.Color(0, 153, 153));
        data4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        data4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                data4ActionPerformed(evt);
            }
        });
        jPanel2.add(data4);
        data4.setBounds(130, 110, 100, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Total da Venda:");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(300, 80, 110, 20);

        total4.setBackground(new java.awt.Color(0, 153, 153));
        total4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        total4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total4ActionPerformed(evt);
            }
        });
        jPanel2.add(total4);
        total4.setBounds(420, 80, 110, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Hora da Venda:");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel11);
        jLabel11.setBounds(300, 110, 100, 20);

        hora4.setBackground(new java.awt.Color(0, 153, 153));
        hora4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        hora4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hora4ActionPerformed(evt);
            }
        });
        jPanel2.add(hora4);
        hora4.setBounds(410, 110, 100, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Forma de Pagamento:");
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 80, 130, 20);

        metodo4.setBackground(new java.awt.Color(0, 153, 153));
        metodo4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        metodo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodo4ActionPerformed(evt);
            }
        });
        jPanel2.add(metodo4);
        metodo4.setBounds(160, 80, 100, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 100, 600, 150);

        Tabela_Vendas.setForeground(new java.awt.Color(0, 102, 102));
        Tabela_Vendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tabela_Vendas);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(40, 270, 470, 150);

        buttonSeven11.setBackground(new java.awt.Color(255, 204, 102));
        buttonSeven11.setText("Voltar");
        buttonSeven11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven11ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSeven11);
        buttonSeven11.setBounds(540, 380, 80, 30);

        buttonSeven12.setBackground(new java.awt.Color(0, 153, 153));
        buttonSeven12.setText("CONSULTAR");
        buttonSeven12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonSeven12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSeven12ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonSeven12);
        buttonSeven12.setBounds(530, 300, 100, 35);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Digite o código da venda para consultar os dados:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 60, 370, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(648, 443));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cpf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpf4ActionPerformed

    private void cliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cliente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cliente4ActionPerformed

    private void vendedor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendedor4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendedor4ActionPerformed

    private void cod4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cod4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cod4ActionPerformed

    private void buttonSeven11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven11ActionPerformed
        this.dispose();
        new Tela_GUI().setVisible(true);
    }//GEN-LAST:event_buttonSeven11ActionPerformed

    private void buttonSeven12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSeven12ActionPerformed
        Model.VendaConsultar.Consultar();
    }//GEN-LAST:event_buttonSeven12ActionPerformed

    private void data4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_data4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_data4ActionPerformed

    private void total4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total4ActionPerformed

    private void hora4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hora4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hora4ActionPerformed

    private void metodo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_metodo4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasConsultar_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasConsultar_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasConsultar_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasConsultar_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendasConsultar_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabela_Vendas;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven11;
    private org.edisoncor.gui.button.ButtonSeven buttonSeven12;
    public static javax.swing.JTextField cliente4;
    public static javax.swing.JTextField cod4;
    public static javax.swing.JTextField cpf4;
    public static javax.swing.JTextField data4;
    public static javax.swing.JTextField hora4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTextField metodo4;
    public static javax.swing.JTextField total4;
    public static javax.swing.JTextField vendedor4;
    // End of variables declaration//GEN-END:variables
}
